"""
Build a self-contained HTML by inlining track_events.json into emergence_scored.html.
Output: emergence_scored_standalone.html — works via file:// or http:// alike.
"""
import sys, os
SRC_HTML  = sys.argv[1] if len(sys.argv) > 1 else "emergence_scored.html"
SRC_JSON  = sys.argv[2] if len(sys.argv) > 2 else "track_events.json"
LOGO_JSON = sys.argv[3] if len(sys.argv) > 3 else "logo_targets.json"
OUT_HTML = SRC_HTML.replace(".html", "_standalone.html")

with open(SRC_HTML, "r", encoding="utf-8") as fh:
    html = fh.read()
with open(SRC_JSON, "r", encoding="utf-8") as fh:
    json_text = fh.read()

# If the HTML still has the old fetch-only block, replace it with an inline-first version.
# Otherwise (new HTML already prefers window.__SCORE), just inject the SCORE tag.
fetch_block_start = "  fetch('track_events.json')"
html_new = html
if fetch_block_start in html:
    fetch_block_end = "    });"
    i0 = html.index(fetch_block_start)
    i1 = html.index(fetch_block_end, i0) + len(fetch_block_end)
    new_block = (
"""  // Inlined score — generated by build_scored.py
  if (window.__SCORE) {
    score = window.__SCORE;
    for (const band in score.events) cursors[band] = 0;
    document.getElementById('loadStatus').textContent =
      'timeline loaded (inline) · ' + Object.values(score.events).reduce((s, e) => s + e.length, 0) +
      ' events · ' + score.duration.toFixed(1) + 's @ ' + score.bpm + ' bpm · click load audio';
    document.getElementById('entry').classList.remove('loading');
  } else {
    fetch('track_events.json').then(r => r.json()).then(data => {
      score = data;
      for (const band in data.events) cursors[band] = 0;
      document.getElementById('loadStatus').textContent =
        'timeline loaded · ' + Object.values(data.events).reduce((s, e) => s + e.length, 0) +
        ' events · ' + data.duration.toFixed(1) + 's @ ' + data.bpm + ' bpm · click load audio';
      document.getElementById('entry').classList.remove('loading');
    }).catch(err => {
      document.getElementById('loadStatus').textContent = 'no timeline (degraded — audio only)';
      document.getElementById('entry').classList.remove('loading');
      console.warn(err);
    });
  }"""
    )
    html_new = html[:i0] + new_block + html[i1:]

# Insert the score (and logo targets, if available) as <script> tags right
# before the main IIFE script.
inject_tag = '<script>\nwindow.__SCORE = ' + json_text + ';\n</script>\n'
if os.path.exists(LOGO_JSON):
    with open(LOGO_JSON, "r", encoding="utf-8") as fh:
        logo_text = fh.read()
    inject_tag += '<script>\nwindow.__LOGO = ' + logo_text + ';\n</script>\n'
script_marker = '<audio id="audioEl"'
mi = html_new.index(script_marker)
html_new = html_new[:mi] + inject_tag + html_new[mi:]

with open(OUT_HTML, "w", encoding="utf-8") as fh:
    fh.write(html_new)

print(f"wrote: {OUT_HTML} ({len(html_new)} bytes)")
